# Generated by Django 4.1.1 on 2023-08-17 20:10

from django.db import migrations, models
import flake_app.fields
import flake_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('flake_app', '0002_alter_comment_user_alter_device_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flake',
            name='over_flake_loc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flake',
            name='over_map_loc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flake',
            name='over_trained_loc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flake',
            name='trained_image',
            field=flake_app.fields.DropboxImageField(blank=True, dropbox_url_field='trained_url', null=True, upload_to=flake_app.models.get_trained_file_location),
        ),
    ]
