# Generated by Django 4.1.1 on 2023-08-17 20:10

from django.db import migrations, models
import flake_app.fields
import flake_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('flake_app', '0003_flake_over_flake_loc_flake_over_map_loc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flake',
            old_name='over_flake_loc',
            new_name='flake_path',
        ),
        migrations.RenameField(
            model_name='flake',
            old_name='over_map_loc',
            new_name='map_path',
        ),
        migrations.RenameField(
            model_name='flake',
            old_name='over_trained_loc',
            new_name='trained_path',
        ),
    ]
