# Generated by Django 3.2.5 on 2023-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flake_app', '0007_auto_20220825_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbn',
            name='capsule',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hbn',
            name='noise',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hbn',
            name='thick',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hbn',
            name='thin',
            field=models.BigIntegerField(default=0),
        ),
    ]
